[masters]
devops-master ansible_host=98.93.79.234 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/t-key.pem

[agents]
devops-agent ansible_host=54.205.16.122 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/t-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
